name: Daily VOC Collection

on:
  push:
    branches: [ "main", "master" ]
  schedule:
    # 매일 오전 9시, 오후 9시 (KST 기준 = UTC+9)
    - cron: '0 0 * * *'   # UTC 00:00 = KST 09:00
    - cron: '0 12 * * *'  # UTC 12:00 = KST 21:00
  workflow_dispatch:  # 수동 실행 가능

permissions:
  contents: write

env:
  CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
  YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
  NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
  NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}

jobs:
  collect-and-analyze:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Install anthropic if not in requirements (it should be)
          pip install anthropic google-play-scraper app-store-scraper google-api-python-client requests pandas
      
      - name: Run Pipeline
        run: |
          # Run collection, analysis, and aggregation
          python main.py --mode all
      
      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "📊 Daily VOC update $(date +'%Y-%m-%d %H:%M')"
            git push
          fi